/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JOptionPane;

/**
 *
 * @author Elise
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Card Drawing Simulation");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        binomRd = new javax.swing.JRadioButton();
        nbinomRd = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        without = new javax.swing.JRadioButton();
        hyper = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MCO2"); // NOI18N

        binomRd.setText("Binomial");
        binomRd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                binomRdItemStateChanged(evt);
            }
        });
        binomRd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binomRdMouseClicked(evt);
            }
        });
        binomRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binomRdActionPerformed(evt);
            }
        });

        nbinomRd.setText("Negative Binomial");
        nbinomRd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nbinomRdItemStateChanged(evt);
            }
        });
        nbinomRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbinomRdActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select an option");

        without.setText("Without replacement");
        without.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                withoutItemStateChanged(evt);
            }
        });
        without.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withoutActionPerformed(evt);
            }
        });

        hyper.setText("Hyper");
        hyper.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hyperItemStateChanged(evt);
            }
        });
        hyper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hyper)
                    .addComponent(without)
                    .addComponent(nbinomRd)
                    .addComponent(binomRd))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(binomRd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbinomRd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(without)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hyper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void binomRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binomRdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binomRdActionPerformed

    private void nbinomRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbinomRdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbinomRdActionPerformed

    private void binomRdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binomRdMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_binomRdMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (binomRd.isSelected()) {
            this.setVisible(false);
            new Binom().setVisible(true);
        } else if (nbinomRd.isSelected()) {
            this.setVisible(false);
            new nBinom().setVisible(true);
        } else if (without.isSelected()) {
            this.setVisible(false);
            new Without().setVisible(true);
        } else if (hyper.isSelected()) {
            this.setVisible(false);
            new nBinom().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Select an option", "Warning", JOptionPane.WARNING_MESSAGE, null);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void withoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withoutActionPerformed

    private void hyperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hyperActionPerformed

    private void binomRdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_binomRdItemStateChanged
        // TODO add your handling code here:
        if(binomRd.isSelected()) {
            nbinomRd.setSelected(false);
            without.setSelected(false);
            hyper.setSelected(false);
        }
    }//GEN-LAST:event_binomRdItemStateChanged

    private void nbinomRdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nbinomRdItemStateChanged
        if(nbinomRd.isSelected()) {
            binomRd.setSelected(false);
            without.setSelected(false);
            hyper.setSelected(false);
        }
    }//GEN-LAST:event_nbinomRdItemStateChanged

    private void withoutItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_withoutItemStateChanged
        if(without.isSelected()) {
            nbinomRd.setSelected(false);
            binomRd.setSelected(false);
            hyper.setSelected(false);
        }
    }//GEN-LAST:event_withoutItemStateChanged

    private void hyperItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hyperItemStateChanged
        if(hyper.isSelected()) {
            nbinomRd.setSelected(false);
            binomRd.setSelected(false);
            without.setSelected(false);
        }
    }//GEN-LAST:event_hyperItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton binomRd;
    private javax.swing.JRadioButton hyper;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nbinomRd;
    private javax.swing.JRadioButton without;
    // End of variables declaration//GEN-END:variables
}
